/**
 * DANH SÁCH VẬT PHẨM MINECRAFT ĐẦY ĐỦ - Minecraft 1.20+
 */

module.exports = {
    '⚔️ Vũ khí': [
        { id: 'netherite_sword', name: 'Kiếm Netherite', icon: '🗡️' },
        { id: 'diamond_sword', name: 'Kiếm Kim Cương', icon: '⚔️' },
        { id: 'iron_sword', name: 'Kiếm Sắt', icon: '⚔️' },
        { id: 'golden_sword', name: 'Kiếm Vàng', icon: '⚔️' },
        { id: 'stone_sword', name: 'Kiếm Đá', icon: '⚔️' },
        { id: 'wooden_sword', name: 'Kiếm Gỗ', icon: '⚔️' },
        { id: 'bow', name: 'Cung', icon: '🏹' },
        { id: 'crossbow', name: 'Nỏ', icon: '🎯' },
        { id: 'trident', name: 'Đinh Ba', icon: '🔱' },
        { id: 'arrow', name: 'Mũi Tên', icon: '➡️' },
        { id: 'spectral_arrow', name: 'Mũi Tên Phát Sáng', icon: '✨' },
        { id: 'shield', name: 'Khiên', icon: '🛡️' },
        { id: 'mace', name: 'Chùy', icon: '🔨' },
        { id: 'totem_of_undying', name: 'Totem Bất Tử', icon: '🗿' },
    ],

    '⛏️ Công cụ': [
        { id: 'netherite_pickaxe', name: 'Cúp Netherite', icon: '⛏️' },
        { id: 'diamond_pickaxe', name: 'Cúp Kim Cương', icon: '⛏️' },
        { id: 'iron_pickaxe', name: 'Cúp Sắt', icon: '⛏️' },
        { id: 'golden_pickaxe', name: 'Cúp Vàng', icon: '⛏️' },
        { id: 'stone_pickaxe', name: 'Cúp Đá', icon: '⛏️' },
        { id: 'wooden_pickaxe', name: 'Cúp Gỗ', icon: '⛏️' },
        { id: 'netherite_axe', name: 'Rìu Netherite', icon: '🪓' },
        { id: 'diamond_axe', name: 'Rìu Kim Cương', icon: '🪓' },
        { id: 'iron_axe', name: 'Rìu Sắt', icon: '🪓' },
        { id: 'golden_axe', name: 'Rìu Vàng', icon: '🪓' },
        { id: 'stone_axe', name: 'Rìu Đá', icon: '🪓' },
        { id: 'wooden_axe', name: 'Rìu Gỗ', icon: '🪓' },
        { id: 'netherite_shovel', name: 'Xẻng Netherite', icon: '🥄' },
        { id: 'diamond_shovel', name: 'Xẻng Kim Cương', icon: '🥄' },
        { id: 'iron_shovel', name: 'Xẻng Sắt', icon: '🥄' },
        { id: 'golden_shovel', name: 'Xẻng Vàng', icon: '🥄' },
        { id: 'stone_shovel', name: 'Xẻng Đá', icon: '🥄' },
        { id: 'wooden_shovel', name: 'Xẻng Gỗ', icon: '🥄' },
        { id: 'netherite_hoe', name: 'Cuốc Netherite', icon: '🌾' },
        { id: 'diamond_hoe', name: 'Cuốc Kim Cương', icon: '🌾' },
        { id: 'iron_hoe', name: 'Cuốc Sắt', icon: '🌾' },
        { id: 'golden_hoe', name: 'Cuốc Vàng', icon: '🌾' },
        { id: 'stone_hoe', name: 'Cuốc Đá', icon: '🌾' },
        { id: 'wooden_hoe', name: 'Cuốc Gỗ', icon: '🌾' },
        { id: 'fishing_rod', name: 'Cần Câu', icon: '🎣' },
        { id: 'flint_and_steel', name: 'Bật Lửa', icon: '🔥' },
        { id: 'shears', name: 'Kéo', icon: '✂️' },
        { id: 'brush', name: 'Cọ Khảo Cổ', icon: '🖌️' },
        { id: 'lead', name: 'Dây Dắt', icon: '🪢' },
        { id: 'name_tag', name: 'Thẻ Tên', icon: '🏷️' },
        { id: 'compass', name: 'La Bàn', icon: '🧭' },
        { id: 'clock', name: 'Đồng Hồ', icon: '🕐' },
        { id: 'spyglass', name: 'Ống Nhòm', icon: '🔭' },
        { id: 'map', name: 'Bản Đồ', icon: '🗺️' },
    ],

    '🛡️ Giáp': [
        { id: 'netherite_helmet', name: 'Mũ Netherite', icon: '⛑️' },
        { id: 'diamond_helmet', name: 'Mũ Kim Cương', icon: '⛑️' },
        { id: 'iron_helmet', name: 'Mũ Sắt', icon: '⛑️' },
        { id: 'golden_helmet', name: 'Mũ Vàng', icon: '⛑️' },
        { id: 'chainmail_helmet', name: 'Mũ Xích', icon: '⛑️' },
        { id: 'leather_helmet', name: 'Mũ Da', icon: '⛑️' },
        { id: 'turtle_helmet', name: 'Mũ Rùa', icon: '🐢' },
        { id: 'netherite_chestplate', name: 'Giáp Netherite', icon: '🦺' },
        { id: 'diamond_chestplate', name: 'Giáp Kim Cương', icon: '🦺' },
        { id: 'iron_chestplate', name: 'Giáp Sắt', icon: '🦺' },
        { id: 'golden_chestplate', name: 'Giáp Vàng', icon: '🦺' },
        { id: 'chainmail_chestplate', name: 'Giáp Xích', icon: '🦺' },
        { id: 'leather_chestplate', name: 'Giáp Da', icon: '🦺' },
        { id: 'netherite_leggings', name: 'Quần Netherite', icon: '👖' },
        { id: 'diamond_leggings', name: 'Quần Kim Cương', icon: '👖' },
        { id: 'iron_leggings', name: 'Quần Sắt', icon: '👖' },
        { id: 'golden_leggings', name: 'Quần Vàng', icon: '👖' },
        { id: 'chainmail_leggings', name: 'Quần Xích', icon: '👖' },
        { id: 'leather_leggings', name: 'Quần Da', icon: '👖' },
        { id: 'netherite_boots', name: 'Giày Netherite', icon: '👢' },
        { id: 'diamond_boots', name: 'Giày Kim Cương', icon: '👢' },
        { id: 'iron_boots', name: 'Giày Sắt', icon: '👢' },
        { id: 'golden_boots', name: 'Giày Vàng', icon: '👢' },
        { id: 'chainmail_boots', name: 'Giày Xích', icon: '👢' },
        { id: 'leather_boots', name: 'Giày Da', icon: '👢' },
        { id: 'elytra', name: 'Elytra', icon: '🪂' },
        { id: 'wolf_armor', name: 'Giáp Sói', icon: '🐺' },
    ],

    '🍎 Thức ăn': [
        { id: 'apple', name: 'Táo', icon: '🍎' },
        { id: 'golden_apple', name: 'Táo Vàng', icon: '🍏' },
        { id: 'enchanted_golden_apple', name: 'Táo Vàng Phù Phép', icon: '✨' },
        { id: 'cooked_beef', name: 'Bò Nướng', icon: '🥩' },
        { id: 'cooked_porkchop', name: 'Heo Nướng', icon: '🥓' },
        { id: 'cooked_mutton', name: 'Cừu Nướng', icon: '🍖' },
        { id: 'cooked_chicken', name: 'Gà Nướng', icon: '🍗' },
        { id: 'cooked_rabbit', name: 'Thỏ Nướng', icon: '🐇' },
        { id: 'cooked_cod', name: 'Cá Tuyết Nướng', icon: '🐟' },
        { id: 'cooked_salmon', name: 'Cá Hồi Nướng', icon: '🐟' },
        { id: 'bread', name: 'Bánh Mì', icon: '🍞' },
        { id: 'cake', name: 'Bánh Kem', icon: '🎂' },
        { id: 'cookie', name: 'Bánh Quy', icon: '🍪' },
        { id: 'pumpkin_pie', name: 'Bánh Bí Ngô', icon: '🥧' },
        { id: 'carrot', name: 'Cà Rốt', icon: '🥕' },
        { id: 'golden_carrot', name: 'Cà Rốt Vàng', icon: '🥕' },
        { id: 'potato', name: 'Khoai Tây', icon: '🥔' },
        { id: 'baked_potato', name: 'Khoai Nướng', icon: '🥔' },
        { id: 'beetroot', name: 'Củ Dền', icon: '🫒' },
        { id: 'melon_slice', name: 'Dưa Hấu', icon: '🍉' },
        { id: 'sweet_berries', name: 'Quả Ngọt', icon: '🫐' },
        { id: 'glow_berries', name: 'Quả Phát Sáng', icon: '✨' },
        { id: 'chorus_fruit', name: 'Quả Chorus', icon: '🍇' },
        { id: 'mushroom_stew', name: 'Súp Nấm', icon: '🥣' },
        { id: 'rabbit_stew', name: 'Súp Thỏ', icon: '🥣' },
        { id: 'dried_kelp', name: 'Tảo Khô', icon: '🌿' },
        { id: 'honey_bottle', name: 'Chai Mật Ong', icon: '🍯' },
    ],

    '💎 Nguyên liệu quý': [
        { id: 'netherite_ingot', name: 'Thỏi Netherite', icon: '⬛' },
        { id: 'diamond', name: 'Kim Cương', icon: '💎' },
        { id: 'emerald', name: 'Ngọc Lục Bảo', icon: '💚' },
        { id: 'gold_ingot', name: 'Thỏi Vàng', icon: '🥇' },
        { id: 'iron_ingot', name: 'Thỏi Sắt', icon: '🔩' },
        { id: 'copper_ingot', name: 'Thỏi Đồng', icon: '🔶' },
        { id: 'amethyst_shard', name: 'Mảnh Thạch Anh', icon: '🟣' },
        { id: 'lapis_lazuli', name: 'Lapis Lazuli', icon: '🔵' },
        { id: 'coal', name: 'Than', icon: '⚫' },
        { id: 'charcoal', name: 'Than Củi', icon: '🪵' },
        { id: 'quartz', name: 'Thạch Anh Nether', icon: '⬜' },
        { id: 'netherite_scrap', name: 'Mảnh Netherite', icon: '🔲' },
        { id: 'ancient_debris', name: 'Mảnh Vụn Cổ Đại', icon: '🟫' },
        { id: 'nether_star', name: 'Ngôi Sao Nether', icon: '⭐' },
        { id: 'heart_of_the_sea', name: 'Trái Tim Biển', icon: '💙' },
        { id: 'dragon_breath', name: 'Hơi Thở Rồng', icon: '🐉' },
        { id: 'ghast_tear', name: 'Nước Mắt Ghast', icon: '😢' },
        { id: 'blaze_rod', name: 'Que Blaze', icon: '🔥' },
        { id: 'blaze_powder', name: 'Bột Blaze', icon: '✨' },
        { id: 'ender_pearl', name: 'Ngọc Ender', icon: '🟢' },
        { id: 'ender_eye', name: 'Mắt Ender', icon: '👁️' },
        { id: 'shulker_shell', name: 'Vỏ Shulker', icon: '🐚' },
        { id: 'phantom_membrane', name: 'Màng Phantom', icon: '👻' },
        { id: 'echo_shard', name: 'Mảnh Vọng Âm', icon: '🔊' },
        { id: 'slime_ball', name: 'Bóng Slime', icon: '🟢' },
        { id: 'magma_cream', name: 'Kem Magma', icon: '🔶' },
    ],

    '🧱 Khối quý': [
        { id: 'netherite_block', name: 'Khối Netherite', icon: '⬛' },
        { id: 'diamond_block', name: 'Khối Kim Cương', icon: '💎' },
        { id: 'emerald_block', name: 'Khối Ngọc Lục Bảo', icon: '💚' },
        { id: 'gold_block', name: 'Khối Vàng', icon: '🥇' },
        { id: 'iron_block', name: 'Khối Sắt', icon: '🔩' },
        { id: 'copper_block', name: 'Khối Đồng', icon: '🔶' },
        { id: 'lapis_block', name: 'Khối Lapis', icon: '🔵' },
        { id: 'redstone_block', name: 'Khối Redstone', icon: '🔴' },
        { id: 'coal_block', name: 'Khối Than', icon: '⚫' },
        { id: 'amethyst_block', name: 'Khối Thạch Anh Tím', icon: '🟣' },
        { id: 'quartz_block', name: 'Khối Thạch Anh', icon: '⬜' },
    ],

    '🏗️ Khối xây dựng': [
        { id: 'stone', name: 'Đá', icon: '🪨' },
        { id: 'cobblestone', name: 'Đá Cuội', icon: '🪨' },
        { id: 'stone_bricks', name: 'Gạch Đá', icon: '🧱' },
        { id: 'deepslate', name: 'Đá Sâu', icon: '⬛' },
        { id: 'deepslate_bricks', name: 'Gạch Đá Sâu', icon: '⬛' },
        { id: 'bricks', name: 'Gạch', icon: '🧱' },
        { id: 'terracotta', name: 'Terracotta', icon: '🟫' },
        { id: 'glass', name: 'Kính', icon: '🪟' },
        { id: 'tinted_glass', name: 'Kính Màu Đậm', icon: '🪟' },
        { id: 'oak_planks', name: 'Ván Gỗ Sồi', icon: '🪵' },
        { id: 'spruce_planks', name: 'Ván Gỗ Vân Sam', icon: '🪵' },
        { id: 'birch_planks', name: 'Ván Gỗ Bạch Dương', icon: '🪵' },
        { id: 'jungle_planks', name: 'Ván Gỗ Rừng', icon: '🪵' },
        { id: 'acacia_planks', name: 'Ván Gỗ Keo', icon: '🪵' },
        { id: 'dark_oak_planks', name: 'Ván Gỗ Sồi Đen', icon: '🪵' },
        { id: 'mangrove_planks', name: 'Ván Gỗ Đước', icon: '🪵' },
        { id: 'cherry_planks', name: 'Ván Gỗ Anh Đào', icon: '🌸' },
        { id: 'bamboo_planks', name: 'Ván Tre', icon: '🎋' },
        { id: 'crimson_planks', name: 'Ván Đỏ Thẫm', icon: '🔴' },
        { id: 'warped_planks', name: 'Ván Cong Vênh', icon: '🔵' },
        { id: 'obsidian', name: 'Obsidian', icon: '⬛' },
        { id: 'crying_obsidian', name: 'Obsidian Khóc', icon: '💜' },
        { id: 'end_stone', name: 'Đá End', icon: '🟨' },
        { id: 'purpur_block', name: 'Khối Purpur', icon: '🟪' },
        { id: 'prismarine', name: 'Prismarine', icon: '🔷' },
        { id: 'sea_lantern', name: 'Đèn Biển', icon: '💡' },
        { id: 'glowstone', name: 'Đá Phát Sáng', icon: '💡' },
    ],

    '🔥 Nether': [
        { id: 'netherrack', name: 'Netherrack', icon: '🔴' },
        { id: 'nether_bricks', name: 'Gạch Nether', icon: '🟫' },
        { id: 'basalt', name: 'Bazan', icon: '⬛' },
        { id: 'blackstone', name: 'Đá Đen', icon: '⬛' },
        { id: 'gilded_blackstone', name: 'Đá Đen Mạ Vàng', icon: '🟨' },
        { id: 'soul_sand', name: 'Cát Linh Hồn', icon: '🟫' },
        { id: 'soul_soil', name: 'Đất Linh Hồn', icon: '🟫' },
        { id: 'magma_block', name: 'Khối Magma', icon: '🔥' },
        { id: 'nether_wart_block', name: 'Khối Mụn Nether', icon: '🔴' },
        { id: 'crimson_stem', name: 'Thân Đỏ Thẫm', icon: '🔴' },
        { id: 'warped_stem', name: 'Thân Cong Vênh', icon: '🔵' },
    ],

    '🧪 Thuốc & Phù phép': [
        { id: 'potion', name: 'Chai Thuốc', icon: '🧪' },
        { id: 'splash_potion', name: 'Thuốc Ném', icon: '💥' },
        { id: 'lingering_potion', name: 'Thuốc Lưu', icon: '☁️' },
        { id: 'glass_bottle', name: 'Chai Thủy Tinh', icon: '🍾' },
        { id: 'nether_wart', name: 'Mụn Nether', icon: '🌿' },
        { id: 'brewing_stand', name: 'Giá Pha Chế', icon: '⚗️' },
        { id: 'cauldron', name: 'Vạc', icon: '🫕' },
        { id: 'enchanted_book', name: 'Sách Phù Phép', icon: '📕' },
        { id: 'enchanting_table', name: 'Bàn Phù Phép', icon: '📚' },
        { id: 'anvil', name: 'Đe', icon: '🔨' },
        { id: 'grindstone', name: 'Đá Mài', icon: '⚙️' },
        { id: 'experience_bottle', name: 'Chai Kinh Nghiệm', icon: '💚' },
        { id: 'bookshelf', name: 'Kệ Sách', icon: '📚' },
    ],

    '🔴 Redstone': [
        { id: 'redstone', name: 'Bụi Redstone', icon: '🔴' },
        { id: 'redstone_torch', name: 'Đuốc Redstone', icon: '🔴' },
        { id: 'redstone_lamp', name: 'Đèn Redstone', icon: '💡' },
        { id: 'lever', name: 'Cần Gạt', icon: '🎚️' },
        { id: 'stone_button', name: 'Nút Đá', icon: '🔘' },
        { id: 'repeater', name: 'Bộ Lặp', icon: '🔁' },
        { id: 'comparator', name: 'Bộ So Sánh', icon: '⚖️' },
        { id: 'observer', name: 'Quan Sát Viên', icon: '👁️' },
        { id: 'piston', name: 'Piston', icon: '🔲' },
        { id: 'sticky_piston', name: 'Piston Dính', icon: '🟢' },
        { id: 'slime_block', name: 'Khối Slime', icon: '🟢' },
        { id: 'honey_block', name: 'Khối Mật Ong', icon: '🟨' },
        { id: 'dispenser', name: 'Máy Phóng', icon: '📤' },
        { id: 'dropper', name: 'Máy Thả', icon: '📥' },
        { id: 'hopper', name: 'Phễu', icon: '🫙' },
        { id: 'tnt', name: 'TNT', icon: '💣' },
        { id: 'note_block', name: 'Khối Nốt Nhạc', icon: '🎵' },
        { id: 'sculk_sensor', name: 'Cảm Biến Sculk', icon: '🔵' },
    ],

    '🚗 Giao thông': [
        { id: 'minecart', name: 'Xe Goòng', icon: '🛒' },
        { id: 'chest_minecart', name: 'Xe Goòng Rương', icon: '📦' },
        { id: 'hopper_minecart', name: 'Xe Goòng Phễu', icon: '🫙' },
        { id: 'tnt_minecart', name: 'Xe Goòng TNT', icon: '💣' },
        { id: 'rail', name: 'Ray', icon: '🛤️' },
        { id: 'powered_rail', name: 'Ray Điện', icon: '⚡' },
        { id: 'detector_rail', name: 'Ray Cảm Biến', icon: '🔴' },
        { id: 'activator_rail', name: 'Ray Kích Hoạt', icon: '🟢' },
        { id: 'oak_boat', name: 'Thuyền Gỗ Sồi', icon: '🛶' },
        { id: 'cherry_boat', name: 'Thuyền Gỗ Anh Đào', icon: '🌸' },
        { id: 'bamboo_raft', name: 'Bè Tre', icon: '🎋' },
        { id: 'saddle', name: 'Yên Ngựa', icon: '🐴' },
        { id: 'iron_horse_armor', name: 'Giáp Ngựa Sắt', icon: '🐴' },
        { id: 'golden_horse_armor', name: 'Giáp Ngựa Vàng', icon: '🐴' },
        { id: 'diamond_horse_armor', name: 'Giáp Ngựa Kim Cương', icon: '🐴' },
    ],

    '🎨 Trang trí': [
        { id: 'torch', name: 'Đuốc', icon: '🔦' },
        { id: 'soul_torch', name: 'Đuốc Linh Hồn', icon: '🔵' },
        { id: 'lantern', name: 'Đèn Lồng', icon: '🏮' },
        { id: 'soul_lantern', name: 'Đèn Linh Hồn', icon: '🔵' },
        { id: 'candle', name: 'Nến', icon: '🕯️' },
        { id: 'end_rod', name: 'Thanh End', icon: '🔦' },
        { id: 'white_carpet', name: 'Thảm Trắng', icon: '⬜' },
        { id: 'red_carpet', name: 'Thảm Đỏ', icon: '🟥' },
        { id: 'blue_carpet', name: 'Thảm Xanh', icon: '🟦' },
        { id: 'white_wool', name: 'Len Trắng', icon: '⬜' },
        { id: 'red_wool', name: 'Len Đỏ', icon: '🟥' },
        { id: 'blue_wool', name: 'Len Xanh', icon: '🟦' },
        { id: 'white_concrete', name: 'Bê Tông Trắng', icon: '⬜' },
        { id: 'red_concrete', name: 'Bê Tông Đỏ', icon: '🟥' },
        { id: 'blue_concrete', name: 'Bê Tông Xanh', icon: '🟦' },
        { id: 'black_concrete', name: 'Bê Tông Đen', icon: '⬛' },
        { id: 'dandelion', name: 'Bồ Công Anh', icon: '🌼' },
        { id: 'poppy', name: 'Hoa Anh Túc', icon: '🌺' },
        { id: 'sunflower', name: 'Hướng Dương', icon: '🌻' },
        { id: 'rose_bush', name: 'Bụi Hồng', icon: '🌹' },
        { id: 'painting', name: 'Tranh', icon: '🖼️' },
        { id: 'item_frame', name: 'Khung Vật Phẩm', icon: '🖼️' },
        { id: 'glow_item_frame', name: 'Khung Phát Sáng', icon: '✨' },
        { id: 'armor_stand', name: 'Giá Giáp', icon: '🗿' },
        { id: 'flower_pot', name: 'Chậu Hoa', icon: '🪴' },
    ],

    '🥚 Trứng Spawn': [
        { id: 'allay_spawn_egg', name: 'Trứng Allay', icon: '🧚' },
        { id: 'axolotl_spawn_egg', name: 'Trứng Axolotl', icon: '🦎' },
        { id: 'bat_spawn_egg', name: 'Trứng Dơi', icon: '🦇' },
        { id: 'bee_spawn_egg', name: 'Trứng Ong', icon: '🐝' },
        { id: 'blaze_spawn_egg', name: 'Trứng Blaze', icon: '🔥' },
        { id: 'cat_spawn_egg', name: 'Trứng Mèo', icon: '🐱' },
        { id: 'chicken_spawn_egg', name: 'Trứng Gà', icon: '🐔' },
        { id: 'cow_spawn_egg', name: 'Trứng Bò', icon: '🐄' },
        { id: 'creeper_spawn_egg', name: 'Trứng Creeper', icon: '💚' },
        { id: 'dolphin_spawn_egg', name: 'Trứng Cá Heo', icon: '🐬' },
        { id: 'enderman_spawn_egg', name: 'Trứng Enderman', icon: '🖤' },
        { id: 'fox_spawn_egg', name: 'Trứng Cáo', icon: '🦊' },
        { id: 'frog_spawn_egg', name: 'Trứng Ếch', icon: '🐸' },
        { id: 'ghast_spawn_egg', name: 'Trứng Ghast', icon: '👻' },
        { id: 'goat_spawn_egg', name: 'Trứng Dê', icon: '🐐' },
        { id: 'horse_spawn_egg', name: 'Trứng Ngựa', icon: '🐴' },
        { id: 'iron_golem_spawn_egg', name: 'Trứng Golem Sắt', icon: '🤖' },
        { id: 'llama_spawn_egg', name: 'Trứng Llama', icon: '🦙' },
        { id: 'panda_spawn_egg', name: 'Trứng Gấu Trúc', icon: '🐼' },
        { id: 'parrot_spawn_egg', name: 'Trứng Vẹt', icon: '🦜' },
        { id: 'pig_spawn_egg', name: 'Trứng Heo', icon: '🐷' },
        { id: 'piglin_spawn_egg', name: 'Trứng Piglin', icon: '🐷' },
        { id: 'polar_bear_spawn_egg', name: 'Trứng Gấu Bắc Cực', icon: '🐻‍❄️' },
        { id: 'rabbit_spawn_egg', name: 'Trứng Thỏ', icon: '🐰' },
        { id: 'sheep_spawn_egg', name: 'Trứng Cừu', icon: '🐑' },
        { id: 'skeleton_spawn_egg', name: 'Trứng Skeleton', icon: '💀' },
        { id: 'slime_spawn_egg', name: 'Trứng Slime', icon: '🟢' },
        { id: 'sniffer_spawn_egg', name: 'Trứng Sniffer', icon: '🦕' },
        { id: 'spider_spawn_egg', name: 'Trứng Nhện', icon: '🕷️' },
        { id: 'turtle_spawn_egg', name: 'Trứng Rùa', icon: '🐢' },
        { id: 'villager_spawn_egg', name: 'Trứng Dân Làng', icon: '👨‍🌾' },
        { id: 'warden_spawn_egg', name: 'Trứng Warden', icon: '👹' },
        { id: 'witch_spawn_egg', name: 'Trứng Phù Thủy', icon: '🧙‍♀️' },
        { id: 'wolf_spawn_egg', name: 'Trứng Sói', icon: '🐺' },
        { id: 'zombie_spawn_egg', name: 'Trứng Zombie', icon: '🧟' },
    ],

    '🌟 Đặc biệt': [
        { id: 'beacon', name: 'Đèn Hiệu', icon: '🔦' },
        { id: 'conduit', name: 'Ống Dẫn', icon: '🌀' },
        { id: 'end_crystal', name: 'Tinh Thể End', icon: '💎' },
        { id: 'dragon_egg', name: 'Trứng Rồng', icon: '🥚' },
        { id: 'dragon_head', name: 'Đầu Rồng', icon: '🐉' },
        { id: 'wither_skeleton_skull', name: 'Đầu Wither', icon: '💀' },
        { id: 'skeleton_skull', name: 'Đầu Skeleton', icon: '💀' },
        { id: 'zombie_head', name: 'Đầu Zombie', icon: '🧟' },
        { id: 'creeper_head', name: 'Đầu Creeper', icon: '💚' },
        { id: 'spawner', name: 'Spawner', icon: '🔲' },
        { id: 'command_block', name: 'Command Block', icon: '📦' },
        { id: 'structure_block', name: 'Structure Block', icon: '🏗️' },
        { id: 'barrier', name: 'Barrier', icon: '🚫' },
        { id: 'debug_stick', name: 'Debug Stick', icon: '🪄' },
        { id: 'bundle', name: 'Túi Đựng', icon: '👜' },
        { id: 'firework_rocket', name: 'Pháo Hoa', icon: '🎆' },
        { id: 'music_disc_cat', name: 'Đĩa Nhạc Cat', icon: '💿' },
        { id: 'music_disc_pigstep', name: 'Đĩa Nhạc Pigstep', icon: '💿' },
        { id: 'music_disc_otherside', name: 'Đĩa Nhạc Otherside', icon: '💿' },
    ],

    '📦 Lưu trữ': [
        { id: 'chest', name: 'Rương', icon: '📦' },
        { id: 'ender_chest', name: 'Rương Ender', icon: '🟣' },
        { id: 'barrel', name: 'Thùng', icon: '🛢️' },
        { id: 'shulker_box', name: 'Hộp Shulker', icon: '📦' },
        { id: 'white_shulker_box', name: 'Hộp Shulker Trắng', icon: '⬜' },
        { id: 'red_shulker_box', name: 'Hộp Shulker Đỏ', icon: '🟥' },
        { id: 'blue_shulker_box', name: 'Hộp Shulker Xanh', icon: '🟦' },
        { id: 'green_shulker_box', name: 'Hộp Shulker Lục', icon: '🟩' },
        { id: 'yellow_shulker_box', name: 'Hộp Shulker Vàng', icon: '🟨' },
        { id: 'black_shulker_box', name: 'Hộp Shulker Đen', icon: '⬛' },
    ],

    '🏠 Công trình': [
        { id: 'crafting_table', name: 'Bàn Chế Tạo', icon: '🔨' },
        { id: 'furnace', name: 'Lò Nung', icon: '🔥' },
        { id: 'blast_furnace', name: 'Lò Nung Cao', icon: '🔥' },
        { id: 'smoker', name: 'Lò Xông Khói', icon: '🍖' },
        { id: 'campfire', name: 'Lửa Trại', icon: '🏕️' },
        { id: 'soul_campfire', name: 'Lửa Trại Linh Hồn', icon: '🔵' },
        { id: 'stonecutter', name: 'Máy Cắt Đá', icon: '⚙️' },
        { id: 'loom', name: 'Khung Dệt', icon: '🧵' },
        { id: 'cartography_table', name: 'Bàn Bản Đồ', icon: '🗺️' },
        { id: 'smithing_table', name: 'Bàn Rèn', icon: '🔨' },
        { id: 'composter', name: 'Thùng Ủ Phân', icon: '🪴' },
        { id: 'lectern', name: 'Bục Giảng', icon: '📖' },
        { id: 'white_bed', name: 'Giường Trắng', icon: '🛏️' },
        { id: 'red_bed', name: 'Giường Đỏ', icon: '🛏️' },
        { id: 'respawn_anchor', name: 'Mỏ Neo Hồi Sinh', icon: '⚓' },
        { id: 'lodestone', name: 'Đá Nam Châm', icon: '🧲' },
    ],
};
